[features]
seeds = false
# [programs.devnet]
# metaplex_anchor_nft = "2DRLpc3UvKwqgZgkjEEzGBw24ThvFZwGtRDzyLjqzScz"

[programs.localnet]
nft_mint = "3bfaUxYjL8PhJbCiw9rxjaijdgyUs8cJNGSufPuaPuKu"

[registry]
# url = "https://api.apr.dev"
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/weibin/.config/solana/id.json"
# cluster = "Localnet"
# wallet = "/Users/weibin/.config/solana/id.json"

# [[test.genesis]]
# address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
# program = "tests/genesis/mpl_token_metadata@1.2.10.so"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# Cs26yebbtfD2wsMmwcpUsNrnvWJ2vzeBRk3CtRJfaHmC